#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


case "$(uname -s)" in

   Darwin)
     npm run lint
     npm run prettier:format
     ;;

   Linux)
     npm run lint
     npm run prettier:format
     ;;

   *)
     ;;
esac